// This file is auto generated by Rollout.io SDK during application build process, it should be committed to you repository as part of your code. For more info please checkout the FAQ at http://support.rollout.io

#if defined(__LP64__) && __LP64__
# define CGFLOAT_TYPE double
# define CGFLOAT_IS_DOUBLE 1
# define CGFLOAT_MIN DBL_MIN
# define CGFLOAT_MAX DBL_MAX
#else
# define CGFLOAT_TYPE float
# define CGFLOAT_IS_DOUBLE 0
# define CGFLOAT_MIN FLT_MIN
# define CGFLOAT_MAX FLT_MAX
#endif
typedef CGFLOAT_TYPE CGFloat;

#if !defined(OBJC_HIDE_64) && TARGET_OS_IPHONE && __LP64__
typedef bool BOOL;
#else
typedef signed char BOOL;
#endif

typedef struct __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak {
  CGFloat a;
  CGFloat b;
  CGFloat c;
  CGFloat d;
  CGFloat tx;
  CGFloat ty;
} __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak;
typedef struct __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 {
  CGFloat width;
  CGFloat height;
} __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4;
typedef struct __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk {
  CGFloat x;
  CGFloat y;
} __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk;
typedef struct __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc {
  __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk origin;
  __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 size;
} __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc;
typedef struct __rollout_dummy_struct__GHuWOX3oOHfwVHsZCzXYetk81W8 {
  __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 contentSize;
  __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc likeButtonFrame;
  __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc auxiliaryViewFrame;
} __rollout_dummy_struct__GHuWOX3oOHfwVHsZCzXYetk81W8;
typedef struct __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 {
  unsigned long location;
  unsigned long length;
} __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0;
typedef struct __rollout_dummy_struct__HALKRW8Uhry$L4O878epBihD5M8 {
  long domain;
  int error;
} __rollout_dummy_struct__HALKRW8Uhry$L4O878epBihD5M8;
typedef struct __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM {
  double latitude;
  double longitude;
} __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM;
typedef struct __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI {
  CGFloat top;
  CGFloat left;
  CGFloat bottom;
  CGFloat right;
} __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI;
typedef struct __rollout_dummy_struct__Y57DLJkVsJBSYcH4BA5C4LUz95k {
  void* ptr;
  long slen;
} __rollout_dummy_struct__Y57DLJkVsJBSYcH4BA5C4LUz95k;
